export const NATIVE_MODULE_PAGES = {
  '/customerManager/TabCustomermanageList': '/pages/modules/customerManager/index',
  '/customerManager/BackmoneyList': '/pages/modules/customerManager/index',
  '/customerManager/delay': '/pages/modules/customerManager/index',
  '/projectManager/TabProjectmanageList': '/pages/modules/projectManager/index',
  '/projectFundPool/TabProjectFundPoolList': '/pages/modules/projectManager/index',
  '/projectFundPool/TabProjectFundPoolChangeLogList': '/pages/modules/projectManager/index',
  '/customerManager/CustomerRetabeTemplate': '/pages/modules/projectManager/index',
  '/projectManager/wechatConfig': '/pages/modules/projectManager/index',
  '/moneyManager/Preparation': '/pages/modules/moneyManager/index',
  '/moneyManager/Refund': '/pages/modules/moneyManager/index',
  '/projectLossRecord/index': '/pages/modules/moneyManager/index',
  '/Manager/bankAccount': '/pages/modules/moneyManager/index',
  '/materialManage/dataCheck': '/pages/modules/materialManage/index',
  '/materialManage/index': '/pages/modules/materialManage/index',
  '/materialManage/copy': '/pages/modules/materialManage/index',
  '/materialManage/douyinViolationScoreRecord': '/pages/modules/materialManage/index',
  '/mediaRebate/index': '/pages/modules/mediaRebate/index',
  '/mediaRebate/DY/fandian/index': '/pages/modules/mediaRebate/index',
  '/mediaRebate/DY/duizhang/index': '/pages/modules/mediaRebate/index',
  '/mediaRebate/DY/performanceDetail/index': '/pages/modules/mediaRebate/index',
  '/mediaRebate/DY/violationDetail/index': '/pages/modules/mediaRebate/index',
  '/mediaRebate/DY/calcDetail/index': '/pages/modules/mediaRebate/index',
  '/CL/index': '/pages/modules/mediaRebate/index',
  '/TX/index': '/pages/modules/mediaRebate/index'
}
